#ifndef _MAPSERVER_VERSION_H
#define _MAPSERVER_VERSION_H

#define MS_VERSION_MAJOR 6
#define MS_VERSION_MINOR 4
#define MS_VERSION_REV 2
#define MS_VERSION "6.4.2"
#define MS_VERSION_NUM  60402 

#endif

